name: exercises_flutter2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  file_picker: ^8.0.5
  open_file: ^3.3.2
  pdf: ^3.11.0
  flutter_pdfview: ^1.3.2
  flutter_image: ^4.1.11
  flutter_cached_pdfview: ^0.4.2
  chakre_pdf_viewer: ^1.1.0
  pdf_render: ^1.4.10
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.13.1
  archive: 3.6.1
#  get_it: 7.7.0
#  injectable: 2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
#  build_runner: 2.4.11
#  injectable_generator: 2.6.1

flutter:
  uses-material-design: true
